/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexTestImport } from './routes/index.test'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const EmployeesEmployeeIdLazyImport = createFileRoute(
  '/employees/$employeeId',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const EmployeesEmployeeIdLazyRoute = EmployeesEmployeeIdLazyImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/employees/$employeeId.lazy').then((d) => d.Route),
)

const IndexTestRoute = IndexTestImport.update({
  id: '/index/test',
  path: '/index/test',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/index/test': {
      id: '/index/test'
      path: '/index/test'
      fullPath: '/index/test'
      preLoaderRoute: typeof IndexTestImport
      parentRoute: typeof rootRoute
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/index/test': typeof IndexTestRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/index/test': typeof IndexTestRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/index/test': typeof IndexTestRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index/test' | '/employees/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index/test' | '/employees/$employeeId'
  id: '__root__' | '/' | '/index/test' | '/employees/$employeeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  IndexTestRoute: typeof IndexTestRoute
  EmployeesEmployeeIdLazyRoute: typeof EmployeesEmployeeIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  IndexTestRoute: IndexTestRoute,
  EmployeesEmployeeIdLazyRoute: EmployeesEmployeeIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/index/test",
        "/employees/$employeeId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/index/test": {
      "filePath": "index.test.tsx"
    },
    "/employees/$employeeId": {
      "filePath": "employees/$employeeId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
